import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { SessionContextProvider } from "./context/session";
import "./globals.css";
import Header from "./header";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="flex h-full">
      <body className={`${roboto.className} flex flex-1 flex-col m-0`}>
        <SessionContextProvider>
          <Header />
          {children}
        </SessionContextProvider>
      </body>
    </html>
  );
}
